name: Security Audit

on:
  push:
    branches:
      - alpha
      - develop
    paths:
      - Cargo.lock
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    branches:
      - alpha
      - develop
    paths:
      - Cargo.lock

jobs:
  security-audit:
    if: |
      github.event.pull_request.draft == false ||
      github.event.action == 'ready_for_review'
    name: security-audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly-2022-07-26
      - uses: Swatinem/rust-cache@v2
      # - run: |
      #     cargo install cargo-audit
      #     cargo audit \
      #       --deny warnings \
      #       --ignore RUSTSEC-2020-0071 \
      #       --ignore RUSTSEC-2023-0033 \
      #       --ignore RUSTSEC-2023-0034 \
      #       --ignore RUSTSEC-2023-0052
