name: Security Audit

on:
  push:
    branches:
      - main
    paths:
      - Cargo.lock
  pull_request:
    branches:
      - main
    paths:
      - Cargo.lock

jobs:
  security-audit:
    name: security-audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly-2022-07-26
      - uses: Swatinem/rust-cache@v1
      - run: |
          cargo install cargo-audit
          cargo audit --deny warnings --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2021-0141
