name: Lint

on:
  push:
    branches:
      - alpha
      - develop
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    branches:
      - alpha
      - develop

jobs:
  fmt:
    if: |
      github.event.pull_request.draft == false ||
      github.event.action == 'ready_for_review'
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
          override: true
          profile: minimal
          toolchain: nightly-2022-07-26
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo build --release
          cargo fmt --all -- --check

  clippy:
    if: |
      github.event.pull_request.draft == false ||
      github.event.action == 'ready_for_review'
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
          override: true
          profile: minimal
          toolchain: nightly-2022-07-26
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy -- -D warnings
