name: Build and publish docker image

on:
  push:
    tags:
      - 'v*.*.*'
env:
  AWS_REGION: us-west-2

jobs:
  build:
    name: Clone, Build, Publish
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            scrolltech/rollup-explorer-backend
          tags: |
            type=semver,pattern={{version}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.PAT_OWNER }}
          password: ${{ secrets.PAT_TOKEN }}

      # build and push to aws ecr
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        id: build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: rollup-explorer-backend
          IMAGE_TAG: ${{ steps.meta.outputs.version }}
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
