name: Unit Test

on:
  push:
    branches:
      - develop
      - main
      - staging
  pull_request:
    branches:
      - develop
      - main
      - staging

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly-2022-07-26
      - uses: Swatinem/rust-cache@v1
      - uses: taiki-e/install-action@nextest
      - run: cargo nextest run --all
